### ISSUE TITLE
Use of SteamVR Input for any and all bindings means this game cannot be played with OpenComposite.

### ISSUE THREAD

**Issue by GeekyGami** [maxvollmer/Half-Life-VR#12]
OpenComposite is used to bypass SteamVR to get better performance on Oculus headsets.
The difference between SteamVR and OpenComposite on most games is very noticeable, and I can tell that it'd make a major difference for this mod.

I think bindings should be entirely accessible at least through the use of a configuration file.
As far as I can tell, the "actions" folder contains only presets on what to look for on bindings that are entirely handled by Steam IVR.

**Comment by maxvollmer** [comment]
I have no plans of supporting this. Feel free to branch and implement yourself, though.
