### ISSUE TITLE
Index Support?

### ISSUE THREAD

**Issue by allbombson** [maxvollmer/Half-Life-VR#13]
Is Index support planned for the future and is there an eta?

**Comment by NoahSchmitz** [comment]
Seems to work on Index just fine, just pick one of the several controller mappings in the SteamVR settings

**Comment by maxvollmer** [comment]
Every HMD and controller that works with SteamVR works with this mod. In fact the mod is entirely oblivious to what hardware you are using. It gets input commands from SteamVR and doesn't care in the least bit if those commands come from an Index, a Vive, a 20€ cardboard thingy or a hacktool that pretends to be VR hardware.
