### ISSUE TITLE
Oculus Touch Controllers not working

### ISSUE THREAD

**Issue by nabiluahmed** [maxvollmer/Half-Life-VR#14]
Hello, I've placed the VR folder in steamapps\common\Half-Life. I was able to patch using the launcher. The game runs properly and I can see and move my hands. However, the game does not detect any button or analog stick inputs from my Oculus Touch controllers (CV1). The controllers are working fine in other games and apps. Key bindings from HL also do not load in Steam VR's Manage Controller Bindings section.

Thank you for looking into it!

**Comment by r3znikovigor** [comment]
Hello.
I have identical problem with HTC Vive controllers.

**Comment by deinlandel** [comment]
Same with HTC Vive. I can walk with wsad on keyboard but controllers don't do anything

**Comment by maxvollmer** [comment]
The mod doesn't come with predefined default bindings. You have to create your own or chose one of the many community made bindings.
