### ISSUE TITLE
No audio (Unknown command: VModEnable)

### ISSUE THREAD

**Issue by henrykohli** [maxvollmer/Half-Life-VR#17]
Hi and thank you for this mod,
sadly the audio isn't working for me.
Right after starting the game it shows these error messages in the upper left corner.
Unknown command: VModEnable
Found walker1, but can't play!
Found walker2, but can't play!
[hlvr_log.txt](https://github.com/maxvollmer/Half-Life-VR/files/4208531/hlvr_log.txt)

I have Audio in other VR games like GTA V and Obduction VR.

I have selected the correct audio device in the steam vr settings "HEADSET" and already tried to disable all audio devices except of the two HTC vive ones.("USB-Audio" and "HTC-Vive"). I also tried to set the Steam VR Audio settings to "MANUAL" and to set it to external speakers or USB-Audio.

I also tried reinstalling Half Life and your mod like this:
-uninstalled Half Life via Steam
-manually deleted the Half Life directory
-installed Half Life via Steam
-run Half Life once to check if Audio works (It works)
-extracted your mod in to the Half Life Directory like this:
%STEAM%\steamapps\common\Half-Life\vr\
-run your launcher and clicked on "Patch Game" and then on "Launch Half Life VR"
I have sound in the main menu. It produces a sound effect when I hover over the menu items.
After Clicking "New Game" I'm on a railway and I hear no sound. Focusing the window by clicking with the mouse on it doesn't help.

**Comment by henrykohli** [comment]
btw I'm using
Steam VR 1.9.16
the regular HTC Vive (not the Pro)
Windows 10

**Comment by henrykohli** [comment]
I found a workaround:
-start a new game
-go to main menu
-save game
-load saved game.
It looks like the audio bug appears only when you press "new game"

**Comment by henrykohli** [comment]
I can't move my character with the htc vive controllers. I can see my hands in game but i can't move. Using the keyboard buttons woks.

**Comment by rockisch** [comment]
I'm having the same issue with the latest version, and the save/load workaround is also working for me.

**Comment by maxvollmer** [comment]
Thanks for reporting! Yep, this is a known issue. Since audio is handled by the engine I have neither any idea what the cause is, nor how to fix it. I won't look into it, as the save/reload workaround seems to work well, and enabling FMOD also solves this.
