### ISSUE TITLE
the game crashes after the resonance casscade

### ISSUE THREAD

**Issue by ItsCadency** [maxvollmer/Half-Life-VR#20]
i play through the game and then after i see the vortigaunts the game just crashes. i wish i could help more but thats really all that happens maybe its because of my settings?

**Comment by ItsCadency** [comment]
i set all the settings back to default and it still happened
i got something that said demoheader.dmf was never closed
maybe that has something to do with it?

**Comment by maxvollmer** [comment]
Please don't ask for support here. Use the #support channel on our discord server or our subreddit. I check issue reports here only very irregularly (as you might have noticed from the fact that it took me 10 days to reply), and no one else from the team or community is active here. This repo is for open source collaboration, not for support. Sorry and thanks!
