### ISSUE TITLE
using the grip feature

### ISSUE THREAD

**Issue by LordReven666** [maxvollmer/Half-Life-VR#21]
So I just use the recommended community bindings for HTC Vive with motion controllers and I have an issue with the grip feature. I can grab things and use the ladders just fine but the problem is the grip only lasts for about a second and then Gordan's hands just release whatever was being held. This makes it very difficult to climb ladders as I am always falling to my death.

**Comment by maxvollmer** [comment]
Please ask on our subreddit or discord. This is not a support forum, there is no community here to help out, and I don't have the time. (Hence my very late response.) Sorry!
