### ISSUE TITLE
Can't run the game

### ISSUE THREAD

**Issue by foxhound525** [maxvollmer/Half-Life-VR#22]
So I used the installer, it autodetects where my steam install of Half-Life is, done and dusted. I run the only exe in the vr folder; HLVRConfig.exe and the launcher/config menu comes up.

I launch the game, and it shows the menu, but doesn't recognise any input from my vive controllers (using OG HTC Vive). A console also shows this;

Console initialized.
Base networking initialized.
"sv_cheats" changed to "1"
Initializing deltas
Protocol version 48
Exe version 1.1.2.2 (valve)
Exe build: 15:17:55 Jul 24 2019 (8308)
128.0 Mb heap
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 1060 6GB/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 451.48
GL_SIZES:  r:8 g:8 b:8 a:0 depth:24
ARB Multitexture extensions found.
4 texture units.  Detail texture supported.
Sound Initialization
Set primary sound buffer format: yes
   2 channel(s)
   16 bits/sample
   11025 bytes/sec
DirectSound initialized
Loaded library demoplayer.dll.
Loaded library core.dll.
Creating fake network channel.
Loaded library core.dll.
DemoPlayer module initialized.
Parsed 153 text messages
WARNING: failed to locate sequence file global
[Half-Life: VR Initializing. Version: 0.6.26]
VR render target size is: 2136, 2376
Successfully loaded custom action ExampleCustomAction: speak "nice command"
Successfully loaded custom action ExampleCustomAction: speak "you are great"
Successfully loaded custom action ExampleCustomAction: speak "magnetic gordon inside"
Successfully loaded custom action ExampleCustomAction: speak "maximum radioactive service for you"
Successfully loaded custom action ExampleCustomAction: speak "to be _period not to be that is the question"
FMOD successfully initialized. Game sounds are now played back using FMOD.
execing hw/geforce.cfg
execing valve.rc
execing language.cfg
execing autoexec.cfg
execing violence.cfg
execing hw/geforce.cfg
execing config.cfg
"sv_aim" changed to "1.000000"
warning: MP3_InitStream(29, media\gamestartup.mp3) failed

It does this every time and I have no idea why. Any ideas?

**Comment by maxvollmer** [comment]
It does this because that's the perfectly normal game console output. Everything is working correctly. You need to select controller bindings. Please use our discord server or our subreddit for support, not this repository. As you notice it took an entire month to get a response. I don't check in here very often, and there is no one else around. On discord and reddit you have the team and an entire community that can help you.
