### ISSUE TITLE
0.6.27 beta installer does not run

### ISSUE THREAD

**Issue by eyeonus** [maxvollmer/Half-Life-VR#23]
Downloaded the .exe directly from here, when launching nothing happens. Checked the task manager, and the process shows up for about a second and then closes itself. Pretty sure there's a crash of some kind happening, but I'm not getting any error message so not sure.

Win10 64-bit

**Comment by maxvollmer** [comment]
Please don't file bug reports here. Use our discord or the subreddit.

**Comment by eyeonus** [comment]
Don't use the thing specifically for reporting issues to report an issue?

Force people to use social media instead?

That's stupid and asinine.
