### ISSUE TITLE
how do i run with other mods

### ISSUE THREAD

**Issue by arceuss** [maxvollmer/Half-Life-VR#25]
i wanna play opposing force in vr

**Comment by Leonetienne** [comment]
that's not an issue with this mod. high issue counts make repos look bad. please email the author himself

**Comment by Technoguyfication** [comment]
> That's not an issue with this mod. High issue counts make repos look bad. Please email the author instead.

Not necessarily. High open/closed issue ratios and high issue resolution time can make repos look bad, this guy is just asking a question. Also, emailing the author puts the burden to answer on one person who probably has other things to be doing, whereas an issue is an open forum where multiple people can answer.

**Comment by arceuss** [comment]
whats his email

**Comment by Notegun** [comment]
Copy the files from the mod and import it in the vr folder. use console to load the beginning map and voila (haven't tested with everything, I think special use triggers don't work)

**Comment by maxvollmer** [comment]
This is not possible.
