### ISSUE TITLE
spanish language?

### ISSUE THREAD

**Issue by ericmoros** [maxvollmer/Half-Life-VR#26]

**Comment by botchGNU** [comment]
I am a little bit confused. Do you want Spanish as an option to be added?

**Comment by maxvollmer** [comment]
Are you referring to HLVRConfig's UI? Or the female scientist audio? In either case if you provide me with translations/recordings, I'll gladly at them, otherwise I have no idea what exactly it is you want.

**Comment by maxvollmer** [comment]
Closing this as OP isn't replying. Feel free to elaborate your request if you want this to be reopened. Thanks!
