### ISSUE TITLE
Oculust rift S

### ISSUE THREAD

**Issue by estalaggmita** [maxvollmer/Half-Life-VR#30]
I can use the oculus rift S and the game correctly tracks hands and headset but I can set the buttons, Joysticks don´t move the character, triggers don't shoot or grab items. I don´t feel like Oculus is supported by this mod but they work so I´m confused. Any help, please?
thanks

**Comment by maxvollmer** [comment]
Sorry, only seeing this now. I cannot provide support here, especially not SteamVR related support. What you are describing is not a mod issue. The mod has absolutely no concept of hardware whatsoever, that is entirely handled by SteamVR. However the next update will come with default bindings which should make things a bit easier. In general, please note that github is not a good place to ask for support, as you might notice by my late reply.
