### ISSUE TITLE
Audio channels are reversed

### ISSUE THREAD

**Issue by randomman254** [maxvollmer/Half-Life-VR#31]
So far everything has worked fine, however, the stereo surround is completely swapped. When I turn, the things emitting sound go around me in the opposite direction. Is there any way to force the audio channels to flip?

**Comment by Fukeung** [comment]
I have the same issue. Sound settings are at default. Using Vive with windows 10 21H2.

**Comment by codeflorist** [comment]
Same issue here with Vive Pro.

**Comment by maxvollmer** [comment]
This is a known issue and will be fixed in the next update.
