### ISSUE TITLE
other resolutions than 800x600?

### ISSUE THREAD

**Issue by whyronimus** [maxvollmer/Half-Life-VR#34]
Hello,

I'd like to increase the resolution I'm playing with but when I choose another than 800x600 from the Options -> Video menu and click "apply", the game closes. When I open it again, the setting is 800x600 again.
Is this the only supported resolution?

**Comment by maxvollmer** [comment]
You are always playing at your headset's resolution. The game window's resolution is not the resolution that the VR image is rendered at.

As for the game window resolution, changing it causes the game to restart, and that causes SteamVR to be unloaded, and that causes SteamVR to shut down the game. An annoying "feature" of SteamVR.

You can start the game with a different resolution by adding this to the command line in Steam. A user friendly option to set the window resolution in HLVRConfig will be in the next update.
