### ISSUE TITLE
"could not load library d:\steamlibrary\steamapps\common\half-life\valve\cl_dlls\client.dll" ???

### ISSUE THREAD

**Issue by drace60** [maxvollmer/Half-Life-VR#36]
I copy pasted the whole thing into the valve folder.. i start the configurator, and then push launch.

then i got this error:

"could not load library d:\steamlibrary\steamapps\common\half-life\valve\cl_dlls\client.dll"

Help :( ??

**Comment by maxvollmer** [comment]
Sorry, only seeing this now. You murdered your Half-Life by copying the mod into your valve folder. I recommend deleting and reinstalling the game.

Half-Life mods always live in their own folder. This mod is no different. You want to end up with `Path/To/Half-Life/vr`.

Please note that github is not a good place to ask for support, as you might notice by my late reply.
