### ISSUE TITLE
HL cannot load client.dll

### ISSUE THREAD

**Issue by mdovgialo** [maxvollmer/Half-Life-VR#4]
I thought about trying to compile this mod and maybe helping a little, but I just couldn't make it work.

I've compiled it using Visual Studio 2017 under windows 10, with v141 toolset (as defined in project). Tried compiling in debug or release modes, x64 or x86.

Compiled every subproject and then put:
* `HLVRLauncher.exe` into `Half-Life/vr` folder
* `opengl32.dll` into `Half-Life/vr` folder
* `client.dll` into `Half-Life/vr/cl_dlls` folder
* `openvr_api.dll` into` Half-Life/vr/cl_dlls` folder
* `hl.dll` into `Half-Life/vr/dlls` folder
* `liblist.gam` into `Half-Life/vr` folder containing:
```
// Valve Game Info file
//  These are key/value pairs.  Certain mods will use different settings.
//
game "Half-Life VR"
startmap "c0a0"
trainmap "t0a0"
mpentity "info_player_deathmatch"
gamedll "dlls\hl.dll"
secure "1"
type "singleplayer_only"
```
Basically folder structure is like this
![image](https://user-images.githubusercontent.com/6193380/30254612-99d7f262-969b-11e7-8e4c-172132262c9b.png)

But every time I run Half Life using HLVRLauncher I get this:
![image](https://user-images.githubusercontent.com/6193380/30254550-b0f1e648-969a-11e7-953c-238d58c88668.png)

When I run hl.exe using console I get this:
```
$ ./hl.exe -game vr
Using breakpad crash handler
Setting breakpad minidump AppID = 70
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197996176914 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197996176914
```

Is there anything I can check why this could be happening? Any tip or hint would be greatly appreciated.

**Comment by formicsapien** [comment]
Do you run the "Half-Life VR" game shortcut that was added to you steam after you reset steam?

**Comment by mdovgialo** [comment]
I didn't think it would work that way!

But when I run it like that I get authors disclaimer about no warranties, and when I click Yes I get this: 
![image](https://user-images.githubusercontent.com/6193380/30254894-a05beb18-969e-11e7-933a-67ed3d3d33d3.png)

**Comment by mdovgialo** [comment]
Also, when I try to copy opengl32.dll manually it's automatically deleted when I run Half-Life VR from Steam shortcut.

**Comment by mdovgialo** [comment]
>However, it says VModEnable isn't a valid command and it doesn't appear on my HMD.

And no disclaimer?

I think client.dll was not loaded in you case.

**Comment by formicsapien** [comment]
[This guy left some instructions that worked for him.](https://www.reddit.com/r/Vive/comments/6z93zj/original_halflife_1_vr_mod_in_development_need/dmu6ixx/)  These didn't work for me though.  I agree, with the client.dll not loading.  You know how to fix that?

**Comment by maxvollmer** [comment]
Closing as no longer relevant. If you still like to help, drop me a message on reddit or join the mod's discord.
