### ISSUE TITLE
Please allow downloading the game without having to own Half-Life on Steam

### ISSUE THREAD

**Issue by Redyn** [maxvollmer/Half-Life-VR#44]
I have the retail version of the game but I'm unable to download the latest versions of the mod as I don't own it on Steam. I don't want to buy the game again to install a free mod.

**Comment by maxvollmer** [comment]
Hi! Unfortunately I do not have the capacity to offer multiple versions of the mod. Releasing on Steam has streamlined the release process, freeing up time and resources to concentrate on bugfixes and feature development. Also this mod has never worked with the retail version of Half-Life, as multiple features require Steam. I highly recommend getting Half-Life on Steam during one of the many Steam sales (Half-Life was under 1USD during the Steam Winter Sale just a few weeks ago). All that said, the mod is open source (heck you are posting this request on github after all), and no one will stop you from building the mod yourself.
