### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by formicsapien** [maxvollmer/Half-Life-VR#5]
The world is too small.  I found an OpenVR variable called "[Camera Scale](https://github.com/ValveSoftware/openvr/blob/b20b25705d8dd82be221fe68a61db36ae7e2608e/samples/unity_keyboard_sample/Assets/SteamVR/readme.txt#L350)" which is supposed to define the world scale.  I can't really find where it's implemented in your mod, but it needs to be adjusted.

This shouldn't be confused with the HEIGHT of the player.  In this mod the height of the player is modified by where the HMD is in real space relative to where it is when you pick it up.  This makes the player smaller or taller depending on where their HMD was when they hit the load key.

**Comment by maxvollmer** [comment]
I will implement dynamic world scale as a setting players can adjust to their liking.
