### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by Redyn** [maxvollmer/Half-Life-VR#50]
I just started HL1VR and I have to say, I'm baffled by the lack of documentation on basic things like controls.

The player guide doesn't even bother mentioning them. The in-game tutorial doesn't explain them either (as it was obviously designed with the original mouse and keyboard controls in mind). So how on earth am I supposed to figure them out?

Some things are obvious, like shooting things with a gun or hitting stuff with the crowbar. But I had to google to learn how to turn on the flashlight. And I still have no idea how to throw grenades or pull boxes.

**Comment by maxvollmer** [comment]
This is a free mod for a game from 1998. That said, feel free to write documentation and share it with the world!

**Comment by Redyn** [comment]
What kind of response is that? I'm not asking for a thick game manual, I just want to know where I am supposed to read about basic things like the controls. Or is it all supposed to be guesswork on the player's part?

**Comment by maxvollmer** [comment]
The default bindings included with the mod were made by community members, not by me.

The bindings - as with every VR game or app on Steam - are visible in the SteamVR bindings menu.

The bindings are also stored as plain text in this repository.

And yes, even if none of the above were true, you could just try all buttons to figure it out yourself. Again, this is a free mod, and you act like a paying customer. Why do you expect others write documentation for you? Why don't you write documentation for others? No one here is being paid, this isn't a transactional relationship. We are peers.
