### ISSUE TITLE
Weapon models

### ISSUE THREAD

**Issue by formicsapien** [maxvollmer/Half-Life-VR#6]
Would you like help at recreating the weapon models?  They could be made with or without the hands attached to them.  I could rip the originals and model them up along with a pair of hands for when Gordon is unarmed.

 Which brings up another point, are you okay with people trying to help you out on this project?  You do state that anyone can use your code with attribution, but why not work together?

**Comment by maxvollmer** [comment]
Any help is very much appreciated. I've sent you an email.

**Comment by formicsapien** [comment]
Awesome.

**Comment by formicsapien** [comment]
I'm leaving this here because I haven't gotten another email from you.

It's taken me many hours to figure out how to decompile then recompile the weapons after modifying them.  I finally figured pretty much all of it out about 5 hours ago, and since then I've been modeling the weapons.  I've got most of them done in an alpha state (several steps required for such).  They're in the right position to be in the place of the controller.  They'll need further work filling in the missing parts on the underside.  I've started working on a couple of them as well.  I'll try to get them all positioned right.  You'll still need to change where the bullets fly so they'll shoot in the right direction and start in the right place.

Would you like me to email what I have so far?

One more thing, I don't know if you saw it, but there's a guy on reddit that fixed a couple of things and did is own release.  I asked them if they would mind helping out on here, but they haven't responded yet.

**Comment by maxvollmer** [comment]
Sorry, I've been quite busy recently. I'll reply to your emails asap.

**Comment by formicsapien** [comment]
I've just completed what I consider "alpha" models for the weapons.  They work well and look pretty good.  There are still quite a few missing sides still, but I've patched up most of 'em.

**Comment by Doommarine23** [comment]
I don't have a VR headset, but do you need any help with this, Formic? I've been doing amateur modelling for quite some time and have a lot of experience with the HL1 engine.

**Comment by formicsapien** [comment]
Hey, @Doommarine23 !  Sorry for not responding to you, I've been on hiatus for this school year.  I imagine I'll come back to getting HL1 back up and running if max keeps working on it.

**Comment by maxvollmer** [comment]
@formicsapien I am slowly, but constantly working on this whenever I find time :) I have posted some progress updates in our discord, and I will push an update to this repository soon. Would love it if you folks could continue working on the weapons. I made a wishlist for them that I posted to discord. @formicsapien, maybe you could invite @Doommarine23 to our channel?

**Comment by rorincloud** [comment]
https://discordapp.com/invite/MxkDZ3E   Permissions will be given when you join in discord.

**Comment by Doommarine23** [comment]
Alright, I joined it

**Comment by maxvollmer** [comment]
Closing because no longer relevant.
