### ISSUE TITLE
Keep getting stuck on walls

### ISSUE THREAD

**Issue by Dementei** [maxvollmer/Half-Life-VR#7]
Hello, just tried out your mod and it seems everytime I bump into a wall or entity or anything, I get stuck inside of it until I try to turn the other way and walk out of it. My guess would be is that since my tracking isn't completely stabilized and the headset acts as the player position in the world (I think), the micro-movements of the headset slightly nudge the player into anything solid if close enough.  Not sure what to do about that, what do you think?

**Comment by mdovgialo** [comment]
Player should not be allowed to push himself into a wall, the world should move with the meatspace movements.

**Comment by formicsapien** [comment]
Mine has always done the same thing.  @mdovgialo does yours not freeze at all when you walk into walls?

**Comment by mdovgialo** [comment]
Yes, I get stuck. With my comment I meant how game should react to player trying to go through walls.

**Comment by maxvollmer** [comment]
How do you get "stuck"? The game can't prevent your body from moving.

**Comment by mdovgialo** [comment]
Game shouldn't allow to player character to enter walls, now characters collision box can enter a wall when you move physically, then you can't move in game until you move in physical space.

Game shouldn't let character enter walls. For player it would look like gameworld moves with players physical movements. e.g: When you try to push your head inside a wall the wall should move away (in gamey players character just stops moving).

**Comment by maxvollmer** [comment]
This has been fixed.
