### ISSUE TITLE
Add rotation

### ISSUE THREAD

**Issue by Mvivant** [maxvollmer/Half-Life-VR#9]
Do you know how to add the rotation ?
I update the 'cmd->viewangles' but it doesn't rotate the view.
Do you have an idea?

**Comment by maxvollmer** [comment]
Add what rotation? You rotate by moving your head and body.

**Comment by Mvivant** [comment]
No I need to rotate the player with controller.
But I did this https://github.com/3DRudder/Half-Life-VR/blob/master/cl_dll/vr_helper.cpp#L297

**Comment by corpusc** [comment]
hopefully this option has been added by now.  or is an easy thing to code.
i find games that require me to get my cord all twisted up to be unplayable.

**Comment by maxvollmer** [comment]
Oh, this absolutely has been added. I just forgot about the github issue.
